CREATE TABLE category(id INT IDENTITY PRIMARY KEY , name VARCHAR(255), url VARCHAR(255));
CREATE TABLE podcast(id INT IDENTITY PRIMARY KEY, categoryId INT FOREIGN KEY REFERENCES category(id), name VARCHAR(255), date DATE, url VARCHAR(255));
